In [12]:
import numpy as np

In [13]:
# Free!!!!
def read_matrix(file_name):
    '''
    Read an alignment matrix stored in a file.
    
    Opens file, the comprehension reads each line in the file iteratively while the .split()
    takes each line and splits on whatever whitespace delimiter it finds. This gives a nested list
    of integers represented as strings. 
    
    Matrix is returned as a 2D NumPy array (dtype arg automatically converts strings to dtype).
    
    
    ARGS
    ----
    filename: file name of a stored alignment matrix
    
    RETURNS
    -------
    2D NumPy array of type int
    '''
    with open(file_name, 'r') as file:              # Open file
        matrix = [line.split() for line in file]    # Read lines and .split() lines into lists of integers
        return np.array(matrix, dtype = int)        # Return 2D array of integers

In [18]:
def main():
    
    # string literals for matrix test files
    test_matrix_files = ['matrix4.txt', 'matrix5.txt']
    # read each matrix; store matrix ndarray objects in a list
    test_matrices = [read_matrix(file) for file in test_matrix_files]

    print(test_matrices[0], end = '\n\n')
    print(test_matrices[1])
    print()
    print(type(test_matrices[0]), end = '\n\n')
    print(type(test_matrices[1]))
    
main()

[[-1  0 -1 -1  5 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 11]
 [-1 -1 -1 -1 -1  0 -1 -1]
 [-1 -1 -1 -1 -1 -1  7 -1]
 [-1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1]]

[[-1  0 -1 -1  4 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1 -1 -1 -1]
 [-1 -1 -1 -1  0  3 -1 -1]
 [-1 -1 -1 -1 -1  0 -1 -1]
 [-1 -1 -1 -1 -1 -1  0 -1]
 [-1 -1 -1 -1 -1 -1 -1  2]
 [-1 -1 -1 -1 -1 -1 -1 -1]]

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>
