In [12]:
import numpy as np

In [13]:
# So free!!!!
def read_matrix(file_name):
    '''
    Read an alignment matrix stored in a file.
    
    Opens file, the comprehension reads each line in the file iteratively while the .split()
    takes each line and splits on whatever whitespace delimiter it finds. This gives a nested list
    of integers represented as strings. 
    
    Matrix is returned as a 2D NumPy array (dtype arg automatically converts strings to dtype).
    
    
    ARGS
    ----
    filename: file name of a stored alignment matrix
    
    RETURNS
    -------
    2D NumPy array of type int
    '''
    with open(file_name, 'r') as file:              # Open file
        matrix = [line.split() for line in file]    # Read lines and .split() lines into lists of integers
        return np.array(matrix, dtype = int)        # Return 2D array of integers

In [50]:
def main():
    
    # string literals for matrix test files
    test_matrix_files = ['matrix4.txt', 'matrix5.txt']
    # read each matrix; store matrix ndarray objects in a list
    test_matrices = [read_matrix(file) for file in test_matrix_files]

    print(test_matrices[0], end = '\n\n')
    print(test_matrices[0].T)
    print(np.argmax(test_matrices[0].T[4]))
    
    print([test_matrices[0].T[i] for i in range(test_matrices[0].T.shape[0])])
    
    print()
    print(np.argmax(test_matrices[0].T[0]))
    print(test_matrices[0].T[0][np.argmax(test_matrices[0].T[0])])
    
    a = np.array([test_matrices[0].T[i][np.argmax(test_matrices[0].T[i])] for i in range(test_matrices[0].T.shape[0])])
    a = np.where(a < 0, 0, a)
    print(a)
    b = np.array([0, 0, 1, 0, 0, 0, 7, 0], dtype = int)
    print(b)
    
    for i in range(len(a)):
        if i == 0 or i == 1:
            continue
        else:
            if a[i] < a[i-1]:
                a[i] = a[i-1]
                
    print(a)
        
    
    
main()

[[-1  0 -1 -1  5 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 11]
 [-1 -1 -1 -1 -1  0 -1 -1]
 [-1 -1 -1 -1 -1 -1  7 -1]
 [-1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1]]

[[-1 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1  0 -1 -1 -1 -1 -1]
 [ 5 -1 -1  0 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 -1]
 [-1 -1 -1 -1 -1  7 -1 -1]
 [-1 -1 -1 11 -1 -1  0 -1]]
0
[array([-1, -1, -1, -1, -1, -1, -1, -1]), array([ 0, -1, -1, -1, -1, -1, -1, -1]), array([-1,  1, -1, -1, -1, -1, -1, -1]), array([-1, -1,  0, -1, -1, -1, -1, -1]), array([ 5, -1, -1,  0, -1, -1, -1, -1]), array([-1, -1, -1, -1,  0, -1, -1, -1]), array([-1, -1, -1, -1, -1,  7, -1, -1]), array([-1, -1, -1, 11, -1, -1,  0, -1])]

0
-1
[ 0  0  1  0  5  0  7 11]
[0 0 1 0 0 0 7 0]
[ 0  0  1  1  5  5  7 11]
