In [76]:
import numpy as np
from icecream import ic

In [77]:
# So free!!!!
def read_matrix(file_name):
    '''
    Read an alignment matrix stored in a file.
    
    Opens file, the comprehension reads each line in the file iteratively while the .split()
    takes each line and splits on whatever whitespace delimiter it finds. This gives a nested list
    of integers represented as strings. 
    
    Matrix is returned as a 2D NumPy array (dtype arg automatically converts strings to dtype).
    
    
    ARGS
    ----
    filename: file name of a stored alignment matrix
    
    RETURNS
    -------
    2D NumPy array of type int
    '''
    with open(file_name, 'r') as file:              # Open file
        matrix = [line.split() for line in file]    # Read lines and .split() lines into lists of integers
        return np.array(matrix, dtype = int)        # Return 2D array of integers

In [85]:
def main():
    
    # string literals for matrix test files
    test_matrix_files = ['matrix4.txt', 'matrix5.txt']
    # read each matrix; store matrix ndarray objects in a list
    test_matrices = [read_matrix(file) for file in test_matrix_files]

    print(test_matrices[0], end = '\n\n')
#     print(test_matrices[0].T)
#     print(np.argmax(test_matrices[0].T[4]))
    
#     print([test_matrices[0].T[i] for i in range(test_matrices[0].T.shape[0])])
    
#     print()
#     print(np.argmax(test_matrices[0].T[0]))
#     print(test_matrices[0].T[0][np.argmax(test_matrices[0].T[0])])
    
#     a = np.array([test_matrices[0].T[i][np.argmax(test_matrices[0].T[i])] for i in range(test_matrices[0].T.shape[0])])
#     a = np.where(a < 0, 0, a)
#     print(a)
#     b = np.array([0, 0, 1, 0, 0, 0, 7, 0], dtype = int)
#     print(b)
    
#     for i in range(len(a)):
#         if i == 0 or i == 1:
#             continue
#         else:
#             if a[i] < a[i-1]:
#                 a[i] = a[i-1]
                
#     print(a)

    chain = np.zeros(test_matrices[0].shape[0], dtype = int)
    print(chain)
    
    for i in range(1, len(chain)):
        ic(i)
        max_dist = 0
        for j in range(0, i):
            ic(j)
            if (chain[j] + test_matrices[0][j][i]) > max_dist:
                max_dist = chain[j] + test_matrices[0][j][i]
        chain[i] = max_dist
    print()
    
    print(chain)
    
        
    
    
main()

ic| i: 1
ic| j: 0
ic| i: 2
ic| j: 0
ic| j: 1
ic| i: 3
ic| j: 0
ic| j: 1
ic| j: 2
ic| i: 4
ic| j: 0
ic| j: 1
ic| j: 2
ic| j: 3
ic| i: 5
ic| j: 0


[[-1  0 -1 -1  5 -1 -1 -1]
 [-1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1  0 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 11]
 [-1 -1 -1 -1 -1  0 -1 -1]
 [-1 -1 -1 -1 -1 -1  7 -1]
 [-1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1 -1 -1 -1]]

[0 0 0 0 0 0 0 0]


ic| j: 1
ic| j: 2
ic| j: 3
ic| j: 4
ic| i: 6
ic| j: 0
ic| j: 1
ic| j: 2
ic| j: 3
ic| j: 4
ic| j: 5
ic| i: 7
ic| j: 0
ic| j: 1
ic| j: 2
ic| j: 3
ic| j: 4
ic| j: 5
ic| j: 6



[ 0  0  1  1  5  5 12 12]


In [52]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])